# Site settings
title: Code Monkey Blog
email: gardenofwine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tidbits from the everyday programming work of Benny Weingaten-Gabbay
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://codemonkeyblog.com" # the base hostname & protocol for your site
twitter_username: gardenofwine
author:
  name: "Benny Weingarten-Gabbay"
  url: "http://codemonkeyblog.com"

# Build settings
markdown: redcarpet
permalink: /:title
source: .
destination: ./_site
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
